[package]
name = "test-git"
version = "0.1.0"
authors = ["Xintao <hunterlxt@live.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
hello_macro = { path = "." }
hello_macro_derive = { path = "./hello_macro_derive" }

[build-dependencies]
cc = "1.0"