[package]
name = "test-rust"
version = "0.1.0"
authors = ["Xintao <hunterlxt@live.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
hyper = "0"
openssl = "0"
hyper-openssl = "0"
tokio = { version = "0.2", features = ["full"] }

[workspace]
members = [
    "async-await-echo",
]